[package]
name = "posvault_query"
version = "0.2.3"
edition = "2024"
description = "Query engine and materialized views for posvault"
license = "MIT"
repository = "https://github.com/mroczect/posvault"

[dependencies]
libvctrl = "2.1.2"
posvault_handler = { path = "../posvault_handler", version = "1.0.0" }
posvault_store = { path = "../posvault_store", version = "1.0.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
