[package]
name = "posvault_auth"
version = "0.2.1"
edition = "2024"
description = "Authentication and RBAC for posvault"
license = "MIT"
repository = "https://github.com/mroczect/posvault"

[dependencies]
posvault_handler = { path = "../posvault_handler", version = "0.2.1" }
age-credentials = "1.0.0"
libage_auth_handler = "0.2"
libage_otp = "0.2"
zeroize = "1.9"
uuid = { version = "1", features = ["v4"] }           
ed25519-dalek = { version = "2", features = ["serde"] } 
rand_core = "0.6"
hex = "0.4.3"

[dev-dependencies]
age_auth = "0.2.0"
librage = "1.1.0"
sha2 = "0.11.0"
