[package]
name = "posvault_sync"
version = "2.0.2"
edition = "2024"
description = "Branch management and synchronisation for posvault"
license = "MIT"
repository = "https://github.com/mroczect/posvault"

[dependencies]
libvctrl = "2.1.2"
posvault_handler = { path = "../posvault_handler", version = "2.0.2" }
posvault_store = { path = "../posvault_store", version = "2.0.2" }

[dev-dependencies]
tempfile = "3"
